SET SERVEROUTPUT ON
DECLARE
EID NUMBER;
FNAME VARCHAR2(20);
LNAME VARCHAR2(20);
SAL NUMBER;
BEGIN
 SELECT FIRST_NAME,LAST_NAME,SALARY INTO FNAME,LNAME,SAL
 FROM EMPLOYEES
 WHERE EMPLOYEE_ID=&EID;
DBMS_OUTPUT.PUT_LINE(FNAME||' '||LNAME||' '||SAL); 
END;
--==============================================================================
--FIND EXPERIENCE
--AND USE EXP TO GIVE HIKE
DECLARE
 EID NUMBER;
 SAL NUMBER;
 T_EXP NUMBER;
 FNAME VARCHAR2(20);
 LNAME VARCHAR2(20);
 FINAL_SAL NUMBER;
BEGIN
 SELECT SALARY,
 ROUND(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12,2) AS TOTAL_EXPERIENCE INTO SAL,T_EXP
 FROM EMPLOYEES
 WHERE EMPLOYEE_ID=&EID;
 
 SELECT FIRST_NAME,LAST_NAME,
 CASE
  WHEN T_EXP BETWEEN 1 AND 5 THEN (SAL+(SAL*0.20))
  WHEN T_EXP BETWEEN 5 AND 10 THEN (SAL+(SAL*0.15))
  ELSE (SAL+(SAL*0.10)) END AS NEW_SAL INTO FNAME,LNAME, FINAL_SAL
  FROM EMPLOYEES
  WHERE EMPLOYEE_ID=&EID;
 DBMS_OUTPUT.PUT_LINE(FNAME||' '||LNAME||' '||SAL||' '||FINAL_SAL); 
END;

--================================================================================================
--01.AMOUNT > BANK BALANCE THEN SHOW INSUFFICIENT
SET SERVEROUTPUT ON
DECLARE
BANK_BAL NUMBER:=15000;
AMT NUMBER:=&AMT;
REMAINING NUMBER;

BEGIN
 IF BANK_BAL > AMT
  THEN
  REMAINING:=BANK_BAL-AMT;
  DBMS_OUTPUT.PUT_LINE('AVAILABLE  --->>>>'||REMAINING);
 ELSE
   DBMS_OUTPUT.PUT_LINE('INSUFFICIENT');
 END IF;
END;
--================================Repeat=================================================
DECLARE
 BANK_BAL NUMBER:=15000;
 AMT NUMBER :=&AMT;
 REMAINING_BAL NUMBER;
BEGIN
    IF BANK_BAL>AMT
    THEN
    REMAINING_BAL:=BANK_BAL-AMT;
   DBMS_OUTPUT.PUT_LINE('WITHDRAWAL'||REMAINING_BAL); 
ELSE
    DBMS_OUTPUT.PUT_LINE('INSUFFIECIENT BALANCE'); 
END IF;
END;
--=============================================================================================


DECLARE
 BANK_BALANCE NUMBER :=15000;
 AMT NUMBER:=&AMT;
 REMAINING_BAL NUMBER;
BEGIN
 IF BANK_BALANCE>AMT
  THEN
   REMAINING_BAL:=BANK_BALANCE-AMT;
   DBMS_OUTPUT.PUT_LINE('AVAILABE'||REMAINING_BAL);
 ELSE  
 DBMS_OUTPUT.PUT_LINE('INSUFFICIENT');
 END IF;
END;
--==========================================================================================









