SET SERVEROUTPUT ON
DECLARE
NUM1 NUMBER:= &NUM1;
NUM2 NUMBER :=&NUM2;
NUM3 NUMBER :=&NUM3;
BEGIN
   IF NUM1>NUM2 ---TRUE,FALSE
   THEN 
    IF NUM1>NUM3 --TRUE ,FALSE
     THEN 
      DBMS_OUTPUT.PUT_LINE('GREATEST NUMBER IS NUM1 '||NUM1);
        ELSE
      DBMS_OUTPUT.PUT_LINE('GREATEST NUMBER IS NUM3'||NUM3);   
          END IF;
ELSIF NUM2>NUM3 THEN
 DBMS_OUTPUT.PUT_LINE('GREATEST NUMBER IS  NUM2 '||NUM2);
ELSE
 DBMS_OUTPUT.PUT_LINE('GREATEST NUMBER IS NUM3 '||NUM3);
 END IF;
END;


--=================================================================================
--02.
SET SERVEROUTPUT ON
DECLARE
NUM1 NUMBER:=&NO1;
NUM2 NUMBER :=&NO2;
NUM3 NUMBER :=&NO3;
BEGIN
 IF NUM1>NUM2 --TRUE
  THEN 
   IF NUM1>NUM3 
     THEN 
       DBMS_OUTPUT.PUT_LINE('NUM1 IS GREATEST '||NUM1);
       ELSE
        DBMS_OUTPUT.PUT_LINE('NUM3 IS GREATEST' ||NUM3);
   END IF;
 ELSIF NUM2>NUM3 THEN
   DBMS_OUTPUT.PUT_LINE('NUM2 IS GREATEST  '||NUM2 );
 ELSE 
  DBMS_OUTPUT.PUT_LINE('NUM3 IS GREATEST '||NUM3 );
 END IF;
END;

--======================================================================
DECLARE
NUM1 NUMBER :=&NO1;
NUM2 NUMBER :=&NO2;
NUM3 NUMBER :=&NO3;
BEGIN
   IF NUM1>NUM2 AND NUM1>NUM3 THEN
   DBMS_OUTPUT.PUT_LINE('NUM1 IS GREATEST '||NUM1);
    ELSE
    
     IF NUM2>NUM1 AND NUM2>NUM3 THEN
     DBMS_OUTPUT.PUT_LINE('NUM2 IS GREATEST '||NUM2);
       ELSE
        IF NUM3>NUM1 AND NUM3>NUM2 THEN
         DBMS_OUTPUT.PUT_LINE('NUM3 IS GREAEST '||NUM3);
END IF;
END IF;
END IF;
END;
--==========================================================================
DECLARE
NUM1 NUMBER :=&NO1;
NUM2 NUMBER :=&NO2;
NUM3 NUMBER :=&NO3;
BEGIN
 IF NUM1>NUM2  --TRUE
 THEN
   IF NUM1>NUM3 THEN
   DBMS_OUTPUT.PUT_LINE('NUM1 IS GREATEST '||NUM1);
    ELSE 
     DBMS_OUTPUT.PUT_LINE('NUM3 IS GREATEST '||NUM3);
     END IF;
ELSIF NUM2 >NUM3 THEN   
 DBMS_OUTPUT.PUT_LINE('NUM2 IS GREATEST '||NUM2);
ELSE
 DBMS_OUTPUT.PUT_LINE('NUM3 IS GREATEST '||NUM3);
END IF;
END;











